session_name: social-embed
start_directory: ./ # load session relative to config location (project root).
before_script: pnpm install
windows:
  - window_name: social-embed
    layout: main-horizontal
    focus: true
    options:
      main-pane-height: 35
    panes:
      - focus: true
      - pane
      - pane
      - pane
  - window_name: lib
    layout: main-horizontal
    options:
      main-pane-height: 35
    start_directory: ./packages/lib
    panes:
      - focus: true
      - pane
      - pane
      - pane
  - window_name: wc
    layout: main-horizontal
    options:
      main-pane-height: 35
    start_directory: ./packages/wc
    panes:
      - focus: true
      - pane
      - pane
      - pane
  - window_name: docs
    layout: main-horizontal
    start_directory: ./packages/site
    options:
      main-pane-height: 35
    panes:
      - focus: true
      - pane
      - pane
      - pane
