session_name: oembed
start_directory: ./ # load session relative to config location (project root).
before_script: yarn workspace @social-embed/wc build
windows:
- window_name: oembed
  layout: main-horizontal
  focus: true
  options:
    main-pane-height: 35
  start_directory: ./
  panes:
  - focus: true
  - pane
  - pane
  - yarn workspace @social-embed/wc test:watch
  - shell_command:
    - '[ -d node_modules ] && yarn'
    - yarn workspace @social-embed/wc build:watch
- window_name: docs
  layout: main-horizontal
  start_directory: ./packages/site
  options:
    main-pane-height: 35
  panes:
  - focus: true
  - pane
  - pane
  - yarn workspace @social-embed/site start
