nodeLinker: node-modules

# https://yarnpkg.com/configuration/yarnrc#checksumBehavior
checksumBehavior: update

# https://yarnpkg.com/configuration/yarnrc#nmHoistingLimits
nmHoistingLimits: workspaces

# https://yarnpkg.com/configuration/yarnrc#enableImmutableInstalls
enableImmutableInstalls: true

yarnPath: .yarn/releases/yarn-4.2.2.cjs
