/**
 * Single search result item with title, excerpt, and sub-results.
 * Renders Pagefind excerpt HTML with <mark> highlighting.
 *
 * Security note: The excerpt HTML contains only <mark> tags generated by
 * Pagefind from our own indexed documentation content, not user input.
 */

import { useState } from "react";
import type { SearchResult, SearchResultItemProps } from "./searchTypes";

/**
 * Individual search result with expandable sub-results.
 */
export function SearchResultItem({
  result,
  isSelected,
  onClick,
  onMouseEnter,
  id,
}: SearchResultItemProps) {
  const [showSubResults, setShowSubResults] = useState(false);
  const hasSubResults = result.sub_results.length > 0;

  return (
    <div
      aria-selected={isSelected}
      className={`
        search-result-item
        rounded-lg transition-all duration-150 cursor-pointer
        ${isSelected ? "search-result-selected" : "search-result-default"}
      `}
      id={id}
      onClick={onClick}
      onKeyDown={(e) => {
        if (e.key === "Enter" || e.key === " ") {
          e.preventDefault();
          onClick();
        }
      }}
      onMouseEnter={onMouseEnter}
      role="option"
      tabIndex={0}
    >
      {/* Main result */}
      <a
        className="block px-3 py-2 no-underline"
        href={result.url}
        onClick={(e) => {
          // Let the parent handle navigation
          e.preventDefault();
          onClick();
        }}
      >
        <div className="font-medium text-[var(--nav-text)] text-sm leading-tight">
          {result.meta.title}
        </div>
        {/* Pagefind excerpt contains <mark> tags from build-time indexing of our content */}
        <div
          className="search-excerpt mt-1 text-xs text-[var(--nav-text-muted)] line-clamp-2 leading-relaxed"
          dangerouslySetInnerHTML={{ __html: result.excerpt }}
        />
      </a>

      {/* Sub-results toggle and list */}
      {hasSubResults && (
        <div className="px-3 pb-2">
          <button
            aria-expanded={showSubResults}
            className="
              flex items-center gap-1 text-xs text-[var(--search-breadcrumb)]
              hover:text-[var(--nav-text-muted)] transition-colors
              bg-transparent border-0 cursor-pointer p-0
            "
            onClick={(e) => {
              e.stopPropagation();
              setShowSubResults(!showSubResults);
            }}
            type="button"
          >
            <svg
              aria-hidden="true"
              className={`w-3 h-3 transition-transform ${showSubResults ? "rotate-90" : ""}`}
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                d="M9 5l7 7-7 7"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
              />
            </svg>
            {result.sub_results.length} section
            {result.sub_results.length > 1 ? "s" : ""}
          </button>

          {showSubResults && (
            <ul className="mt-2 space-y-1 list-none m-0 p-0">
              {result.sub_results.map((sub) => (
                <li key={sub.id}>
                  <a
                    className="
                      block px-2 py-1.5 rounded text-xs no-underline
                      bg-[var(--search-subresult-bg)] hover:bg-[var(--search-result-hover-bg)]
                      transition-colors
                    "
                    href={sub.url}
                    onClick={(e) => e.stopPropagation()}
                  >
                    <span className="text-[var(--nav-text-muted)] font-medium">
                      # {sub.title}
                    </span>
                    {/* Sub-result excerpt from Pagefind indexing */}
                    <span
                      className="search-excerpt block mt-0.5 text-[var(--search-breadcrumb)] line-clamp-1"
                      dangerouslySetInnerHTML={{ __html: sub.excerpt }}
                    />
                  </a>
                </li>
              ))}
            </ul>
          )}
        </div>
      )}
    </div>
  );
}

/**
 * Extract the title from a search result.
 * Utility function for accessibility descriptions.
 */
export function getResultTitle(result: SearchResult): string {
  return result.meta.title || result.url;
}
