/**
 * Single search result item with title, excerpt, and sub-results.
 * Renders titles and excerpts as HTML with <mark> highlighting.
 *
 * Security note: The HTML contains only <mark> tags generated by
 * Pagefind/mock data from our own indexed documentation content, not user input.
 */

import { useState } from "react";
import type {
  SearchResult,
  SearchResultItemProps,
  SearchSubResult,
} from "./searchTypes";

/** Maximum number of sub-results to show in inline mode */
const INLINE_SUBRESULTS_LIMIT = 3;

/**
 * Thin sub-results to limit shown in inline mode (Pagefind-style).
 * Takes the first N sub-results which are already sorted by relevance.
 */
export function thinSubResults(
  subResults: SearchSubResult[],
  limit = INLINE_SUBRESULTS_LIMIT,
): SearchSubResult[] {
  return subResults.slice(0, limit);
}

/**
 * Breadcrumb segment overrides for acronyms and special cases.
 * Keys are lowercase, values are the display text.
 */
export const BREADCRUMB_OVERRIDES: Record<string, string> = {
  api: "API",
  wc: "WC",
};

/**
 * Generate a breadcrumb path from URL.
 * e.g., "/wc/providers/youtube/" → "WC > Providers > Youtube"
 */
export function urlToBreadcrumb(url: string): string {
  const parts = url
    .replace(/^\//, "") // Remove leading slash
    .replace(/\/$/, "") // Remove trailing slash
    .replace(/#.*$/, "") // Remove anchor
    .split("/")
    .filter(Boolean);

  if (parts.length === 0) return "Home";

  return parts
    .map((part) => {
      const lowerPart = part.toLowerCase();
      // Check for override first
      if (BREADCRUMB_OVERRIDES[lowerPart]) {
        return BREADCRUMB_OVERRIDES[lowerPart];
      }
      // Capitalize first letter, handle kebab-case
      return part
        .split("-")
        .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
        .join(" ");
    })
    .join(" > ");
}

/**
 * Individual search result with configurable sub-results display.
 * Supports three display modes: inline, toggle, and breadcrumbs.
 */
export function SearchResultItem({
  result,
  isSelected,
  onClick,
  onMouseEnter,
  id,
  subResultsDisplay = "toggle",
  selectedSubIndex = -1,
  onSubResultMouseEnter,
  onSubResultClick,
}: SearchResultItemProps) {
  const [showSubResults, setShowSubResults] = useState(false);
  const hasSubResults = result.sub_results.length > 0;

  // For inline mode, limit to top 3 sub-results
  const displayedSubResults =
    subResultsDisplay === "inline"
      ? thinSubResults(result.sub_results)
      : result.sub_results;

  // Determine if main result (not a sub-result) is selected
  const isMainSelected = isSelected && selectedSubIndex === -1;

  return (
    <div
      aria-selected={isSelected}
      className="search-result-item rounded-lg transition-all duration-150"
      id={id}
      role="option"
      tabIndex={-1}
    >
      {/* Main result - biome-ignore needed as this div delegates keyboard to inner link */}
      {/* biome-ignore lint/a11y/noStaticElementInteractions: Keyboard events delegate to focusable link inside */}
      <div
        className={`
          cursor-pointer rounded-lg transition-all duration-150
          ${isMainSelected ? "search-result-selected" : isSelected ? "" : "search-result-default"}
        `}
        onClick={onClick}
        onKeyDown={(e) => {
          if (e.key === "Enter" || e.key === " ") {
            e.preventDefault();
            onClick();
          }
        }}
        onMouseEnter={onMouseEnter}
      >
        <a
          className="block px-3 py-2 no-underline"
          href={result.url}
          onClick={(e) => {
            e.preventDefault();
            onClick();
          }}
        >
          {/* Breadcrumbs display: show path above title */}
          {subResultsDisplay === "breadcrumbs" && (
            <div className="text-xs text-[var(--search-breadcrumb)] mb-0.5">
              {urlToBreadcrumb(result.url)}
            </div>
          )}
          <div
            className="font-medium text-[var(--nav-text)] text-sm leading-tight"
            dangerouslySetInnerHTML={{ __html: result.meta.title }}
          />
          {/* Title and excerpt contain <mark> tags from Pagefind/mock data */}
          <div
            className="search-excerpt mt-1 text-xs text-[var(--nav-text-muted)] line-clamp-2 leading-relaxed"
            dangerouslySetInnerHTML={{ __html: result.excerpt }}
          />
        </a>
      </div>

      {/* Sub-results: Toggle mode (current default behavior) */}
      {subResultsDisplay === "toggle" && hasSubResults && (
        <div className="px-3 pb-2">
          <button
            aria-expanded={showSubResults}
            className="
              flex items-center gap-1 text-xs text-[var(--search-breadcrumb)]
              hover:text-[var(--nav-text-muted)] transition-colors
              bg-transparent border-0 cursor-pointer p-0
            "
            onClick={(e) => {
              e.stopPropagation();
              setShowSubResults(!showSubResults);
            }}
            type="button"
          >
            <svg
              aria-hidden="true"
              className={`w-3 h-3 transition-transform ${showSubResults ? "rotate-90" : ""}`}
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                d="M9 5l7 7-7 7"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
              />
            </svg>
            {result.sub_results.length} section
            {result.sub_results.length > 1 ? "s" : ""}
          </button>

          {showSubResults && (
            <ul className="mt-2 space-y-1 list-none m-0 p-0">
              {result.sub_results.map((sub, subIndex) => {
                const isSubSelected =
                  isSelected && selectedSubIndex === subIndex;
                return (
                  <li key={sub.id}>
                    <a
                      className={`
                        block px-2 py-1.5 rounded text-xs no-underline transition-colors
                        ${isSubSelected ? "search-result-selected" : "bg-[var(--search-subresult-bg)] hover:bg-[var(--search-result-hover-bg)]"}
                      `}
                      data-selected={isSubSelected || undefined}
                      href={sub.url}
                      onClick={(e) => {
                        e.stopPropagation();
                        e.preventDefault();
                        onSubResultClick?.(subIndex);
                      }}
                      onMouseEnter={() => onSubResultMouseEnter?.(subIndex)}
                    >
                      <span className="text-[var(--nav-text-muted)] font-medium">
                        #{" "}
                        <span dangerouslySetInnerHTML={{ __html: sub.title }} />
                      </span>
                      {/* Sub-result title and excerpt contain <mark> tags */}
                      <span
                        className="search-excerpt block mt-0.5 text-[var(--search-breadcrumb)] line-clamp-1"
                        dangerouslySetInnerHTML={{ __html: sub.excerpt }}
                      />
                    </a>
                  </li>
                );
              })}
            </ul>
          )}
        </div>
      )}

      {/* Sub-results: Inline mode (Pagefind-style, always expanded) */}
      {subResultsDisplay === "inline" && hasSubResults && (
        <ul className="px-3 pb-2 space-y-1 list-none m-0 p-0">
          {displayedSubResults.map((sub, subIndex) => {
            const isSubSelected = isSelected && selectedSubIndex === subIndex;
            return (
              <li key={sub.id}>
                <a
                  className={`
                    flex items-start gap-1.5 px-2 py-1 rounded text-xs no-underline transition-colors
                    ${isSubSelected ? "search-result-selected" : "hover:bg-[var(--search-result-hover-bg)]"}
                  `}
                  data-selected={isSubSelected || undefined}
                  href={sub.url}
                  onClick={(e) => {
                    e.stopPropagation();
                    e.preventDefault();
                    onSubResultClick?.(subIndex);
                  }}
                  onMouseEnter={() => onSubResultMouseEnter?.(subIndex)}
                >
                  <span
                    aria-hidden="true"
                    className="text-[var(--search-breadcrumb)] flex-shrink-0 mt-px"
                  >
                    ⤷
                  </span>
                  <span className="flex-1 min-w-0">
                    <span className="text-[var(--nav-text-muted)] font-medium">
                      <span dangerouslySetInnerHTML={{ __html: sub.title }} />
                    </span>
                    <span
                      className="search-excerpt block mt-0.5 text-[var(--search-breadcrumb)] line-clamp-1"
                      dangerouslySetInnerHTML={{ __html: sub.excerpt }}
                    />
                  </span>
                </a>
              </li>
            );
          })}
          {result.sub_results.length > INLINE_SUBRESULTS_LIMIT && (
            <li className="px-2 text-xs text-[var(--search-breadcrumb)]">
              +{result.sub_results.length - INLINE_SUBRESULTS_LIMIT} more
              section
              {result.sub_results.length - INLINE_SUBRESULTS_LIMIT > 1
                ? "s"
                : ""}
            </li>
          )}
        </ul>
      )}

      {/* Sub-results: Breadcrumbs mode doesn't show nested items */}
      {/* The breadcrumb path is shown above the title instead */}
    </div>
  );
}

/**
 * Extract the title from a search result (strips HTML tags).
 * Utility function for accessibility descriptions.
 */
export function getResultTitle(result: SearchResult): string {
  const title = result.meta.title || result.url;
  // Strip HTML tags repeatedly to handle malformed nested tags like <scr<script>ipt>
  let clean = title;
  let prev: string;
  do {
    prev = clean;
    clean = clean.replace(/<[^>]*>/g, "");
  } while (clean !== prev);
  return clean;
}
