name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, "20.x"]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: project - install
        run: pnpm install --frozen-lockfile

      - name: "puppeteer: Install browsers"
        run: pnpm dlx puppeteer browsers install

      - name: pnpm biome format .
        run: pnpm biome format .

      - name: pnpm biome lint .
        run: pnpm biome lint .

      - name: pnpm biome check .
        run: pnpm biome check .

      - name: build
        run: pnpm build

      - name: test
        run: pnpm test
