name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, "20.x"]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: project - install
        run: yarn --immutable

      - name: yarn biome format .
        run: yarn biome format .

      - name: yarn biome lint .
        run: yarn biome lint .

      - name: yarn biome check .
        run: yarn biome check .

      - name: build
        run: yarn build

      - name: test
        run: yarn test
