name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, "20.x", "22.x", "24.x"]

    steps:
      - name: Disable AppArmor
        # Disable AppArmor's restricted user namespaces on Ubuntu 23.10+ so chrome sandboxes work
        # https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
        shell: bash
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: project - install
        run: pnpm install --frozen-lockfile

      - name: "playwright: Install browsers"
        run: pnpm dlx playwright install --with-deps

      - name: pnpm biome format .
        run: pnpm biome format .

      - name: pnpm biome lint .
        run: pnpm biome lint .

      - name: pnpm biome check .
        run: pnpm biome check .

      - name: build
        run: pnpm build

      - name: test
        run: pnpm test
